mainSections = ["post"]
description = "Eureka is a elegant and powerful theme for Hugo."

repoURL = ""
# If it is a Github repo, leave blank
repoEditURL = ""

# E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
siteType = "Person"
icon = "images/icon.png"
publisherName = "Example publisher"
publisherLogo = ""

[hero]
  slogan = "Let It Be :P"
  # Specify the image name in `assets/images/` folder.
  imgLeft = "images/left.jpg"
  imgRight = "images/right.jpg"

[comment]
  # Options: disqus and commento.
  platform = "disqus"

  [comment.disqus]
    shortname = "hishark777"

  [comment.commento]
    # If self-hosting, please enter the url (e.g. https://commento.example.com) here. Otherwise leave empty. 
    url = ""