# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Eureka"
license = "MIT"
licenselink = "https://github.com/wangchucheng/hugo-eureka/blob/master/LICENSE"
description = "Eureka is a feature-rich and highly customizable Hugo theme."
homepage = "https://www.wangchucheng.com/en/docs/eureka/"
tags = ["blog", "Responsive", "Simple", "Personal", "Light", "Dark", "Mobile", "Fast", "Disqus", "Google analytics", "Syntax highlighting", "Highlighting", "Multilingual", "Modern", "Font awesome", "Fontawesome", "Documentation", "Docs", "Seo"]
features = ["Blog", "Responsive", "Documentation", "Light", "Dark"]
min_version = "0.74.0"

authors = [
  {name = "C. Wang", homepage = "https://www.wangchucheng.com/"},
  {name = "R. Ma", homepage = "https://ruiqima.com/"}
]
